# yaml-language-server: $schema=https://raw.githubusercontent.com/cooperspencer/gickup/refs/heads/main/gickup_spec.json

source:
  github:
    - user: actions
destination:
  # Local backup will not work in GitHub Actions,
  # but it's here for demonstration purposes
  local:
    - path: /tmp
      structured: true
