# action.yml
name: 'Gickup Action'
description: 'A GitHub Action for backing up any git repositories using gickup'
branding:
  icon: 'award'
  color: 'green'

inputs:
  config:
    description: 'The gickup configuration file'
    default: '.gickup/gickup.yml'
  dryrun:
    description: 'Run gickup in dryrun mode'
    required: false
    default: 'false'
  debug:
    description: 'Run gickup in debug mode'
    required: false
    default: 'false'
  github-token:
    description: 'The GitHub token or personal access token'
    required: false
    default: '${{ github.token }}'
  env:
    description: 'The Environment variables to pass to gickup'
    required: false
    default: '{}'
  vars:
    description: 'The Variables to pass to gickup'
    required: false
    default: '{}'
  secrets:
    description: 'The Secrets to pass to gickup'
    required: false
    default: '{}'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/socheatsok78/gickup-action:next'
