name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run gickup
      uses: ./
      with:
        dryrun: 'true'
        debug: 'true'
        env: ${{ toJson(env) }}
        vars: ${{ toJson(vars) }}
        secrets: ${{ toJson(secrets) }}
